### ISSUE TITLE
Line 15 & 16 of the adduser script are split and should be a single line.

### ISSUE THREAD

**Issue by Nitesedge** [shivajid/hwx-isilon#2]
"isi auth groups create --name=hadoop --add-user=hdfs --add-user=mapred --add-user=hbase --add-user=storm --add-user=falcon --add-user=accumulo --add
-user=spark --zone=$1"

should be:
"isi auth groups create --name=hadoop --add-user=hdfs --add-user=mapred --add-user=hbase --add-user=storm --add-user=falcon --add-user=accumulo --add-user=spark --zone=$1"

**Comment by shivajid** [comment]
Can you verfiy, I have fixed this.

**Comment by Nitesedge** [comment]
confirmed
